 <style>
   th,td{
     padding:10px;
   }
 </style>
```{r echo=FALSE,message=FALSE}

library(dplyr)
library(knitr)
WORKING_PATH <- "/Users/garidor/Desktop/bandits-rl-project"

dat <- read.csv(file=paste(WORKING_PATH, "/results/free_obs_raw_results/free_obs_experiment_raw_results.csv", sep=""))
p1_algs <- as.list(unique(dat['P1.Alg']))$P1.Alg
p2_algs <- as.list(unique(dat['P2.Alg']))$P2.Alg
agent_algs <- as.list(unique(dat['Agent.Alg']))$Agent.Alg
memory_sizes <- sort(as.list(unique(dat['Memory.Size']))$Memory.Size, decreasing=TRUE)
time_horizons <-  as.list(unique(dat['Time.Horizon']))$Time.Horizon
time_horizons <- c(1000, 5000, 10000, 15000)
priors <- as.list(unique(dat['Prior']))$Prior


ZERO_ONE_CUTOFF <- 0.1
```

```{r echo=FALSE, xtable, results="asis"}

concise_alg_rep <- function(alg) {
  if (alg == "ThompsonSampling") {
    return("TS")
  } else if (alg == "DynamicEpsilonGreedy") {
    return("DEG")
  } else if (alg == "DynamicGreedy") {
    return("DG")
  }
}

concise_agent_rep <- function(agent_alg) {
  if (agent_alg == "HardMax") {
    return("HM")
  } else if (agent_alg == "HardMaxWithRandom") {
    return("HMR")
  } else if (agent_alg == "SoftMax") {
    return("SM")
  }
}

get_agent_rep <- function(repre) {
  res <- c()
  for(a in repre) {
    res <- c(res, concise_agent_rep(a))
  }
  return(res)
}

algs <- c("ThompsonSampling", "DynamicEpsilonGreedy", "DynamicGreedy")
options(xtable.sanitize.text.function=identity)
options(xtable.caption.placement="top")

alg_pairs <- c("ThompsonSampling", "DynamicEpsilonGreedy", "ThompsonSampling", "DynamicGreedy", "DynamicGreedy", "DynamicEpsilonGreedy") #"ThompsonSampling", "ThompsonSampling", "DynamicEpsilonGreedy", "DynamicEpsilonGreedy", "DynamicGreedy", "DynamicGreedy")
#print("Reported means are for principal 1 which is the first algorithm listed in the pair for each column<br>")
#print("In each cell, first line is mean, second line is variance, third line is % of the time that market share > 0.1 or market share < 0.9")
library(xtable)
for (memory in memory_sizes) {
for (prior in priors) {
    for (j in 1:length(time_horizons)) {
      results <- matrix(nrow=length(agent_algs), ncol=(length(alg_pairs) / 2))
    colnames(results) <- c(paste(concise_alg_rep(alg_pairs[1]), concise_alg_rep(alg_pairs[2]), sep=" vs "), paste(concise_alg_rep(alg_pairs[3]), concise_alg_rep(alg_pairs[4]), sep=" vs "), paste(concise_alg_rep(alg_pairs[5]), concise_alg_rep(alg_pairs[6]), sep=" vs ")) #paste(concise_alg_rep(alg_pairs[7]), concise_alg_rep(alg_pairs[8]), sep=" vs "), paste(concise_alg_rep(alg_pairs[9]), concise_alg_rep(alg_pairs[10]), sep=" vs "), paste(concise_alg_rep(alg_pairs[11]), concise_alg_rep(alg_pairs[12]), sep=" vs "))
    rownames(results) <- get_agent_rep(agent_algs)
    for (i in 1:length(agent_algs)) {
      agent_alg <- agent_algs[i]
      time <- time_horizons[j]
      for (k in 1:length(alg_pairs)) {
        if (k %% 2 == 0) { next }
          p1alg = alg_pairs[k]
          p2alg = alg_pairs[k+1]
          filtered_dat <- filter(dat, P1.Alg == p1alg & P2.Alg == p2alg & Memory.Size == memory & Prior == prior & Agent.Alg == agent_alg & Time.Horizon == time)
          if (nrow(filtered_dat) == 0) {
            next
          }
          share <- filtered_dat$Market.Share.for.P1
          test <- t.test(share)
          cin <- signif(test$conf.int[2] - mean(share), digits=1)
          shares <- sum(share >= (1 - ZERO_ONE_CUTOFF) | share <= ZERO_ONE_CUTOFF, na.rm=TRUE) / nrow(filtered_dat)
          shares_percent <- signif(shares * 100, digits=2)
          cv_high <- qchisq(.975, df=length(share) - 1)
          cv_low <- qchisq(.025, df=length(share) - 1)
          lower_var <- signif((length(share) - 1) * var(share) / cv_high, digits=1)
          high_var <- signif((length(share) - 1) * var(share) / cv_low, digits=1)
          results[i, (k+1)/2] <- paste("<b>",signif(mean(share), digits=2), "</b> +/-", cin, "<br>Var:", signif(var(share), digits=2), "<br>", shares_percent, "%")
      }
    }
      tab <-xtable(results, caption=paste("Results for", "t=",time, prior, "Memory=", memory))
      print(tab, type="html")
  }
  }
}

```

